params:
  seed: 42
  algo:
    name: sac
  env:
    clip_actions: 1.0

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [256, 128, 64]
      activation: relu
      
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  config:
    name: ur5-driect_SAC
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    normalize_input: True
    reward_shaper:
      scale_value: 1.0

    max_epochs: 10000
    num_steps_per_episode: 8
    save_best_after: 500
    save_frequency: 1000
    gamma: 0.99
    init_alpha: 1
    alpha_lr: 5e-3
    actor_lr: 5e-4
    critic_lr: 5e-4
    critic_tau: 5e-3
    batch_size: 256
    learnable_temperature: True
    num_warmup_steps: 10 # total number of warmup steps: num_actors * num_steps_per_episode * num_warmup_steps
    replay_buffer_size: 100000
    num_actors: 64
